version: '3.8'

services:
  infosphere-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: infosphere
    ports:
      - "3306:3306"
    volumes:
      - ./configure/initializer/infosphere.sql:/docker-entrypoint-initdb.d/schema.sql

  infosphere-app:
    image: devliveorg/infosphere:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://infosphere-mysql:3306/infosphere
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    restart: always
    ports:
      - "19099:19099"
    depends_on:
      - infosphere-mysql
    volumes:
      - ./configure/docker/application.properties:/opt/app/infosphere/configure/application.properties
