[package]
name = "infosphere-desktop"
version = "2026.0.0"
description = "InfoSphere 桌面客户端"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-window-state = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", default-features = false, features = ["json", "tls"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
