name: Before checker with maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  before_checker_loading:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo 'Before checker loading'

  before_checker_style:
    runs-on: ubuntu-latest
    needs:
      - before_checker_loading
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Maven Checker Style
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: chmod 755 ./mvnw
      - run: ./mvnw clean install checkstyle:checkstyle -Dspotbugs.skip -Dgpg.skip -DskipTests=true -Dskip.yarn

  before_checker_bugs:
    runs-on: ubuntu-latest
    needs:
      - before_checker_style
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Maven Checker Bugs
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: chmod 755 ./mvnw
      - run: ./mvnw clean install spotbugs:spotbugs -Dcheckstyle.skip -Dgpg.skip -DskipTests=true -Dskip.yarn

  before_checker_package:
    runs-on: ubuntu-latest
    needs:
      - before_checker_loading
      - before_checker_style
      - before_checker_bugs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Maven Checker Package
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: chmod 755 ./mvnw
      - run: ./mvnw clean install package -Dspotbugs.skip -Dgpg.skip -Dcheckstyle.skip
